# Generated by Django 3.2.4 on 2021-12-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
